blank_issues_enabled: false
contact_links:
  - name: 新功能投票
    url: https://github.com/zenith-minecraft-launcher/zmcl-launcher/discussions/categories/%E6%8A%95%E7%A5%A8-votes
    about: 新功能将在下一个版本更新中上线，前往投票页面为你想要的新功能投票。
  - name: Q&A
    url: https://github.com/zenith-minecraft-launcher/zmcl-launcher/discussions/categories/q-a
    about: 在这里提出问题，将会有工作人员或其他玩家为你解答。
  - name: 进入官方QQ群
    url: https://qm.qq.com/q/BfdHrC2iY0
    about: 想第一时间获取官方信息？加入我们的QQ群即可！
  - name: 前往Zenith启动器官网
    url: https://zenith.mkserver.xin
    about: 看看我们的官网也是一个不错的选择！
