name: "Minecraft 崩溃"
description: "ZMCL 提示 “Minecraft 出现错误”，或游戏崩溃"
title: "[MC崩溃]"
labels: [新提交]
type:[bug]
body:
  - type: checkboxes
    id: "yml-1"
    attributes:
      label: "检查项"
      description: "请逐个检查下列项目，并勾选确认。"
      options:
        - label: "**我所启动的游戏不是整合包，且未安装任何 Mod。** 安装 Mod 后的崩溃基本不是 ZMCL 导致的，请 **不要** 提交反馈。你可以前往相关社区群求助，但这里不是求助的地方……"
          required: false
        - label: "**我已确认该崩溃是启动器本身造成，非游戏/模组问题。**"
          required: true
        - label: "我已在 [Issues 页面](./issues) 中搜索，确认了这一 Bug 未被提交过。"
          required: true

  - type: textarea
    id: "yml-2"
    attributes:
      label: 描述
      description: "详细描述具体表现。"
    validations:
      required: true

  - type: textarea
    id: "yml-3"
    attributes:
      label: ZMCL 错误报告、日志与附件
      description: "上传 ZMCL 提供的错误报告（在崩溃时选择导出错误报告）。如果没有，也可以上传 ZMCL 文件夹中的日志文件。"
      placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
    validations:
      required: true

  - type: textarea
    id: "yml-4"
    attributes:
      label: 补充信息（可选）
      description: "如有其他启动器对比、截图等可以粘贴在这里"
      placeholder: "粘贴截图、对比启动日志等补充内容"
    validations:
      required: false
