name: "[旧版] 综合 Bug 反馈"
description: "遇见了与启动器功能相关的 Bug"
type: "Bug"
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已在 [Issues 页面](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过"
      required: true
    - label: "我确认只是全部选中而没有[仔细确认](https://github.com/PCL-Community/PCL2-CE/issues?q=is%3Aissue+)就直接提交了这个 Issue，并且同意这个 Issue 可以直接被关闭"
      required: false
    - label: "我确认正在使用当前更新分支的最新版 PCL CE，若不是，此 Issue 可能会被直接关闭（更新方式：启动器 `设置-关于-软件更新` 检查更新，或在 [Releases](https://github.com/PCL-Community/PCL2-CE/releases) 页面下载）"
      required: true
    - label: "我确认会详细描述我所遇到的问题，并附上日志和截图，而不是随便填点东西敷衍了事。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述该 Bug 的具体表现。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 重现步骤
    description: "详细描述要怎么操作才能再次触发这个 Bug。"
    placeholder: |
      示例：
      1、点击 xxxx
      2、往下滚，然后点击 xxxx
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 日志与附件
    description: "在问题发生后立即使用 `设置-查看日志-导出日志` 并上传导出的压缩包。**若手动关掉了启动器或启动器直接崩溃，请重启之后使用 `导出全部日志` 而不是 `导出日志`，否则导出的日志可能不包含故障关键信息。**"
    placeholder: |
      先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。
      如果有相关截图或文件，也请一并上传。
      请勿自行判断是否需要日志，日志文件并不仅仅包含发生错误的信息，还可能包含其它关键信息。
      如果缺少相关日志用于分析问题，此 Issue 可能会被直接关闭。
  validations:
    required: true
