name: "优化建议"
description: "对 ZMCL 已有功能的小幅度优化或改进建议。"
title: "[优化]: "
labels: [新提交]
type: "优化"
body:
  - type: checkboxes
    id: "yml-1"
    attributes:
      label: "检查项"
      description: "请逐个检查下列项目，并勾选确认。"
      options:
        - label: "我已在 [Issues 页面](./issues) 中搜索，确认了这一建议未被提交过"
          required: true
        - label: "我确认只是全部选中而没有仔细确认就直接提交了这个 Issue，并且同意这个 Issue 可以直接被关闭"
          required: false
        - label: "我确认我所描述的改进是现实的、有理有据的，而不是临时起意"
          required: true
        - label: "我已知悉开发团队不对这类 Issue 的完成时间作出任何保证，并有足够耐心等待处理；若出现催促、质问等行为，此 Issue 可能会被直接关闭"
          required: true

  - type: textarea
    id: "yml-2"
    attributes:
      label: 描述
      description: "详细描述具体需要优化哪些地方，要改成怎样的。"
    validations:
      required: true

  - type: textarea
    id: "yml-3"
    attributes:
      label: 原因
      description: "详细描述你为什么需要这项优化，这有助于开发者评估它的优先度。"
      placeholder: |
        示例：
        这项优化让我可以更方便地 xxxx。
        如果没有这项优化，我每次都必须 xxxx，让操作变得很麻烦。
    validations:
      required: false
